### ISSUE TITLE
container masalasi

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [BekzodLolayev/bek-sign-up-form#1]
![image](https://user-images.githubusercontent.com/79502241/140022836-c01da079-dcb4-45d3-8144-a33b67426b24.png)
bu yerdagi bitta div ortiqcha, qo'shmasangiz ham bo'ladi, uni "container" still berish orqali to'g'irlasa bo'ladi

**Comment by BekzodLolayev** [comment]
to'g'rilandi
