### ISSUE TITLE
background of container

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [BekzodLolayev/bek-sign-up-form#2]
![image](https://user-images.githubusercontent.com/79502241/140023111-fe8f4098-4bfd-409a-9ee3-306490d871a7.png)
bu yerda containerga berilgan background-color sahifaga to'liq yoyilmayapti? Buni sababi nima deb o'ylaysiz

**Comment by BekzodLolayev** [comment]
to'g'riloandi
