### ISSUE TITLE
giving height to elements

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [BekzodLolayev/bek-sign-up-form#3]
![image](https://user-images.githubusercontent.com/79502241/140023519-b7d138e5-b818-43c3-8a44-a2e80f8411cd.png)
odatda containerga height berilmaydi. Chunki container uning ichida elementlarga qarab kengayib torayishi kerak

![image](https://user-images.githubusercontent.com/79502241/140023643-0e2cf8ea-50a9-4612-8a80-16e16b7a4608.png)
O'zi elementlarga height bermagan yaxshi, (agar undagi content static bo'lmasa, shu holatda ham min-height beriladi), bu yuqoridagiga o'xshab biror narsa toshib ketishiga olib kelishi mumkin, buni padding bilani to'g'irlagan yaxshi

**Comment by BekzodLolayev** [comment]
to'g'rilandi
