### ISSUE TITLE
styles of container

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [BekzodLolayev/bek-sign-up-form#4]
![image](https://user-images.githubusercontent.com/79502241/140024204-73169eab-4387-4ccb-b3b2-8574ae00095c.png)
container va container-inside stillarini bitta divga berish mumkin.
containerning stillarini yana bir o'ylab ko'ring, ustoz bergan tavsiyalarni eslang

**Comment by BekzodLolayev** [comment]
1 ta divga 2 ta klass berish mumkin, container stillarini boshqa ishlarda qo'llaganman, hozir bu maketga tog'ri keladigfan qilib mosladim
